FROM node:11.15-alpine@sha256:1ea975c6ba5be52074af83445658b060d82fc03bbf70b74137c3e2b5452cee4f as build

RUN apk update && \
  apk add git openssh python

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

ENV REACT_APP_BE_HOST /api

COPY /package-lock.json /package.json /usr/src/app/

RUN npm install

COPY ./ /usr/src/app

RUN npm test || true

RUN npm run-script build

FROM nginx:1.15.8-alpine@sha256:e0292d158b6b353fde34909243a4886977cb9d1abb8a8a5fef9e0ff7138dd3e2

RUN apk update && apk add ca-certificates

COPY --from=build /usr/src/app/build /usr/share/nginx/html

COPY /entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

COPY ./nginx/default-no-oauth.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/sslcerts

COPY ./nginx/*.pem /etc/nginx/sslcerts/

RUN mkdir -p /usr/share/nginx/html/resources/img

COPY ./nginx/compressed.mov /usr/share/nginx/html/resources/img

#RUN wget -O /microscanner https://get.aquasec.com/microscanner && \
#    chmod +x /microscanner

#RUN [ "8e01415d364a4173c9917832c2e64485d93ac712a18611ed5099b75b6f44e3a5  /microscanner" = "$(sha256sum /microscanner)" ]

#ARG MICROSCANNER_TOKEN

#RUN if [ -z "$MICROSCANNER_TOKEN" ]; then echo "MICROSCANNER_TOKEN not set using --build-arg MICROSCANNER_TOKEN=<token>"; exit 1; else : ; fi

#RUN /microscanner $MICROSCANNER_TOKEN && \
#    rm -rf /microscanner