export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_CONFIG_FAILED';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const SET_IS_POSTS_SHOWN = 'SET_IS_POSTS_SHOWN'

